
services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "29092:9092"
    environment:
      # --- KRaft (Zookeeper 없음) ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # 단일 노드 개발용
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # KRaft 클러스터 ID (고정값 사용)
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  collector:
    build: ./collector
    depends_on:
      - kafka
    env_file: .env
    restart: unless-stopped
    command: ["python", "-u", "main.py"]
    environment:
    - PYTHONUNBUFFERED=1


  spark:
    build: ./spark
    depends_on:
      - kafka
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./storage:/data
    environment:
      HOME: /tmp
      SPARK_SUBMIT_OPTS: "-Divy.cache.dir=/tmp/.ivy2 -Divy.home=/tmp/.ivy2"


